### ISSUE TITLE
Hide .edtz files in styles.css

### ISSUE THREAD

**Issue by antoniotejada** [antoniotejada/obsidian-edit-history#10]
This `CSS` snippet hides the `edtz` files from the file explorer.

```css
.tree-item.nav-file:has(div[data-path$=edtz]) {
  display: none;
}
```

Obsidian v1.4.9

_Originally posted by @gapmiss in https://github.com/antoniotejada/obsidian-edit-history/issues/2#issuecomment-1714866617_

**Comment by gapmiss** [comment]
Was having problems with this CSS rule and have since changed it to:

```css
.tree-item.nav-file > div[data-path$=edtz] {
  display: none;
}
```

Still needs more testing to make sure the CSS specificity does not effect other menu items.
